version: '3'
services:
  webapp:
    container_name: webapp
    image: ahmetarslann/docker_test:latest
    ports:
      - "80:80"
    depends_on:
      - restapi
    networks:
      - backend
  restapi:
    container_name: restapi
    image: ahmetarslann/messenger-app:latest
    ports:
      - "8080:8080"
    networks:
      - backend
networks:
  backend: {}