name: Dockerize, Publish and Compose

on:
  push:
    branches:
      - main

jobs:
  build_publish_and_compose:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Latest Docker Image
      run: docker pull ahmetarslann/docker_test:latest

    - name: Build Docker Image
      run: docker buildx build -t ahmetarslann/docker_test:latest .

    - name: Push Docker Image to Docker Hub
      run: docker buildx build --push -t ahmetarslann/docker_test:latest .
      
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo  chmod +x /usr/local/bin/docker-compose
        docker-compose version
      
    - name: Deploy with Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d
        
    - name: Check Container Status
      run: docker-compose ps
        
    - name: Test Web Application
      run: |
       curl http://localhost


